# Generated by Django 4.2.13 on 2024-06-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
